function VREXOStrokePlist = importHandedness(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  VREXOSTROKEPLIST = importHandedness(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  VREXOSTROKEPLIST = importHandedness(FILE, SHEET) reads from the specified
%  worksheet.
%
%  VREXOSTROKEPLIST = importHandedness(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  VREXOStrokePlist = importHandedness("C:\Users\Alex\Dropbox\Catholic U\VR_EXO_Stroke\Participants\VR_EXO_Stroke_Plist.xlsx", "Sheet1", [1, 15]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 30-Jan-2023 11:39:20

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% Get number of rows in Plist
temp = xlsread(workbookFile);
nrow = length(temp)+1;

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [1, nrow];
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 7);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":G" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Var1", "ParticipantID", "Var3", "Var4", "Var5", "Var6", "SideAffected"];
opts.SelectedVariableNames = ["ParticipantID", "SideAffected"];
opts.VariableTypes = ["char", "string", "char", "char", "char", "char", "categorical"];

% Specify variable properties
opts = setvaropts(opts, ["Var1", "ParticipantID", "Var3", "Var4", "Var5", "Var6"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "ParticipantID", "Var3", "Var4", "Var5", "Var6", "SideAffected"], "EmptyFieldRule", "auto");

% Import the data
VREXOStrokePlist = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":G" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    VREXOStrokePlist = [VREXOStrokePlist; tb]; %#ok<AGROW>
end

end